services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    env_file:
      - ./app/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-courier}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-courierpassword}
      POSTGRES_DB: ${POSTGRES_DB:-courierdb}
    volumes:
      - ./app:/var/www/html
      - ./docker/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./docker/postgresql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    env_file:
      - ./app/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-courier}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-courierpassword}
      POSTGRES_DB:  ${POSTGRES_DB:-courierdb}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata:
